### ISSUE TITLE
Server crashes when trying to create a policy

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#294]
```
NoMethodError (undefined method `all' for Location:Class):
    app/models/policy.rb:157: in `block (2 levels) in load_results'
    app/models/policy.rb:155:in `map!'
    app/models/policy.rb:155:in `block in load_results'
    app/models/policy.rb:154:in `each'
    app/models/policy.rb:154:in `load_results'
    app/models/policy.rb:122:in `check_all'
    app/models/policy.rb:69:in `can?'
    app/models/policy.rb:77:in `can_delegate?'
    app/models/policy.rb:187:in `block (4 levels) in validate_owner_permissions'
    app/models/policy.rb:186:in `each'
    app/models/policy.rb:186:in `block (3 levels) in validate_owner_permissions'
    app/models/policy.rb:182:in `each'
    app/models/policy.rb:182:in `block (2 levels) in validate_owner_permissions'
    app/models/policy.rb:181:in `each'
    app/models/policy.rb:181:in `block in validate_owner_permissions'
    app/models/policy.rb:180:in `each'
    app/models/policy.rb:180:in `validate_owner_permissions'
    app/controllers/policies_controller.rb:30:in `block in create' app/controllers/policies_
```

**Comment by mmuller** [comment]
Ok in Version: 0.4-pre5
