### ISSUE TITLE
Error when accessing a device with an old manifest

### ISSUE THREAD

**Issue by nekron** [instedd/cdx#359]
If the manifest hasn't been updated, and the core list of fields changes, the device crashes saying that there is a custom field that should be defined in the manifest.

Show a warning, and disable custom field mappings, but let the user see the device.

**Comment by matiasgarciaisaia** [comment]
As of 38d8b5f771fb7af5d00b3142d2b04f69921890a7 it throws:

```
ActionView::Template::Error (Custom field test.patient_age must be defined in manifest.):
     8:   .col
     9:     = fields_for(:device) do |d|
    10:       = d.fields_for(:custom_mappings) do |m|
    11:         - custom_fields = @device.current_manifest.fields.select(&:custom?)
    12:         - custom_fields.each do |field|
    13:           .control-group
    14:             = m.label field.target_field, class: 'control-label'
  app/models/custom_manifest_field.rb:5:in `for'
  app/models/manifest_field.rb:9:in `for'
  app/models/manifest.rb:89:in `block in fields'
  app/models/manifest.rb:88:in `each'
  app/models/manifest.rb:88:in `inject'
  app/models/manifest.rb:88:in `fields'
  app/views/devices/_custom_mappings.haml:11:in `block (2 levels) in _app_views_devices__custom_mappings_haml___1217062184138734410_70192902718340'
  app/views/devices/_custom_mappings.haml:10:in `block in _app_views_devices__custom_mappings_haml___1217062184138734410_70192902718340'
  app/views/devices/_custom_mappings.haml:9:in `_app_views_devices__custom_mappings_haml___1217062184138734410_70192902718340'
  app/views/devices/_form.haml:41:in `block in _app_views_devices__form_haml__522465756052066432_70192872464080'
  app/views/devices/_form.haml:1:in `_app_views_devices__form_haml__522465756052066432_70192872464080'
  app/views/devices/edit.haml:6:in `_app_views_devices_edit_haml___3518701619421838450_70192893794480'
```

**Comment by pmallol** [comment]
Ok in Version: 0.11-pre4
